title: Hanbin Luo's Homepage
page-top-title: Hanbin Luo
top-section-bg-text: Signal and Information Processing | Processor Architecture | Embedded Systems
avatar-image: static/assets/img/pic0.jpg
backgrounds:
  - static/assets/background/background_0.jpg
  - static/assets/background/background_3.jpg
  - static/assets/background/background_5.jpg

background-interval-ms: 3000
background-overlay: 0.52
copyright-text: '&copy; Hanbin Luo 2026. All Rights Reserved.'
github-link:
  text: GitHub
  href: https://github.com/HanbinLuo
bilibili-link:
  text: Bilibili
  href: https://space.bilibili.com/353011170?spm_id_from=333.1007.0.0
cnblogs-link:
  text: 博客园
  href: https://www.cnblogs.com/luohanbin
lab-link:
  text: ACE Lab
  href: https://acelab-shu.github.io/
license-link:
  text: License
  href: https://github.com/HanbinLuo/HanbinLuo.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: 首页
    title: Hanbin Luo
    href: '#page-top'
  - id: projects
    nav: 项目经历
    title: 项目经历
    icon: bi-cpu-fill
  - id: honors
    nav: 竞赛荣誉
    title: 竞赛荣誉
    icon: bi-award-fill
  - id: skills
    nav: 专业技能
    title: 专业技能
    icon: bi-tools
